exp_name: sac
seed: 42
torch_deterministic: False
cuda: True
env_id: 7dof_hit
total_timesteps: 1e6
buffer_size: 1e6
gamma: 0.99
tau : 0.01
batch_size: 256
learning_starts: 100
policy_lr: 1e-4
q_lr: 3e-4,
policy_frequency: 1
target_network_frequency: 2
noise_clip: 0.5
alpha: 0.2
autotune: True
