exp_name: sac
seed: 40
torch_deterministic: False
cuda: True
env_id: 7dof-hit
total_timesteps: 1e6
buffer_size: 50000
gamma: 0.99
tau : 0.005
batch_size: 1024
learning_starts: 512
policy_lr: 0.0001
q_lr: 0.0003
policy_frequency: 1
target_network_frequency: 2
noise_clip: 0
alpha: 0.2
autotune: True
offline_size: 10000

